param(
    [ValidateSet("sample", "com-youtube", "roadNet-CA", "amazon0601")]
    [string]$Graph = "sample",
    [switch]$Download,
    [int]$MaxEdges = 0
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$rawDir = Join-Path $repoRoot "data\raw"
New-Item -ItemType Directory -Force -Path $rawDir | Out-Null
@"
# data/raw

Large SNAP datasets are intentionally ignored by git.

Expected filenames:
- roadNet-CA.txt
- amazon0601.txt
- com-youtube.ungraph.txt

Sampled files generated by scripts/download_snap_sample.ps1 can be used for smoke benchmarks.
"@ | Set-Content -Encoding UTF8 -Path (Join-Path $rawDir "README.md")

$snap = @{
    "com-youtube" = @{
        Url = "https://snap.stanford.edu/data/bigdata/communities/com-youtube.ungraph.txt.gz"
        File = "com-youtube.ungraph.txt.gz"
    }
    "roadNet-CA" = @{
        Url = "https://snap.stanford.edu/data/roadNet-CA.txt.gz"
        File = "roadNet-CA.txt.gz"
    }
    "amazon0601" = @{
        Url = "https://snap.stanford.edu/data/amazon0601.txt.gz"
        File = "amazon0601.txt.gz"
    }
}

if ($Graph -eq "sample") {
    $samplePath = Join-Path $rawDir "sample_snap.txt"
    @"
# Tiny SNAP-style sample for smoke tests
100 200
200 300
300 100
300 400
400 200
"@ | Set-Content -Encoding UTF8 -Path $samplePath
    Write-Host "Created $samplePath"
    Write-Host "Run: python src/benchmark.py --config project_spec.yaml --edges-path data/raw/sample_snap.txt"
    exit 0
}

$entry = $snap[$Graph]
$target = Join-Path $rawDir $entry.File
if (-not $Download) {
    Write-Host "SNAP URL: $($entry.Url)"
    Write-Host "Target path: $target"
    Write-Host "Use -Download to fetch it. These files can be large."
    exit 0
}

Invoke-WebRequest -Uri $entry.Url -OutFile $target
Write-Host "Downloaded $target"

$plainName = [System.IO.Path]::GetFileNameWithoutExtension($entry.File)
$plainPath = Join-Path $rawDir $plainName
$samplePath = if ($MaxEdges -gt 0) { Join-Path $rawDir ("{0}.sample{1}.txt" -f ([System.IO.Path]::GetFileNameWithoutExtension($plainName)), $MaxEdges) } else { $plainPath }

$inputStream = [System.IO.File]::OpenRead($target)
try {
    $gzipStream = [System.IO.Compression.GzipStream]::new($inputStream, [System.IO.Compression.CompressionMode]::Decompress)
    $reader = [System.IO.StreamReader]::new($gzipStream)
    $writer = [System.IO.StreamWriter]::new($samplePath, $false, [System.Text.Encoding]::UTF8)
    try {
        $edgeCount = 0
        while (($line = $reader.ReadLine()) -ne $null) {
            if ($line.Trim().Length -eq 0) { continue }
            if (-not $line.TrimStart().StartsWith("#")) {
                $edgeCount += 1
            }
            $writer.WriteLine($line)
            if ($MaxEdges -gt 0 -and $edgeCount -ge $MaxEdges) { break }
        }
    } finally {
        $writer.Dispose()
        $reader.Dispose()
    }
} finally {
    $inputStream.Dispose()
}

Write-Host "Prepared $samplePath"
Write-Host "Run: python src/benchmark.py --config project_spec.yaml --edges-path `"$samplePath`" --graph-name $Graph --gpu"
